namespace CommunityHelper.Domain.Entities;

/// <summary>
/// A volunteering need published by an organization.
/// Only the fields required by the current read model are modelled — the full
/// shape described in the PRD (skills, capacity, status) is added as the
/// features that need it are built.
/// </summary>
public sealed class Opportunity
{
    private Opportunity(
        string id,
        string title,
        string description,
        string location,
        bool isRemote,
        DateTime startsAtUtc)
    {
        Id = id;
        Title = title;
        Description = description;
        Location = location;
        IsRemote = isRemote;
        StartsAtUtc = startsAtUtc;
    }

    public string Id { get; private set; }
    public string Title { get; }
    public string Description { get; }
    public string Location { get; }
    public bool IsRemote { get; }
    public DateTime StartsAtUtc { get; }

    public static Opportunity Create(
        string title,
        string description,
        string location,
        bool isRemote,
        DateTime startsAtUtc,
        string? id = null)
    {
        if (string.IsNullOrWhiteSpace(title))
        {
            throw new ArgumentException("Title is required.", nameof(title));
        }

        if (string.IsNullOrWhiteSpace(description))
        {
            throw new ArgumentException("Description is required.", nameof(description));
        }

        if (!isRemote && string.IsNullOrWhiteSpace(location))
        {
            throw new ArgumentException("On-site opportunities require a location.", nameof(location));
        }

        return new Opportunity(
            id ?? string.Empty,
            title.Trim(),
            description.Trim(),
            location.Trim(),
            isRemote,
            startsAtUtc);
    }

    /// <summary>
    /// Assigns the identifier generated by the persistence layer on insert.
    /// </summary>
    public void SetId(string id)
    {
        if (string.IsNullOrWhiteSpace(id))
        {
            throw new ArgumentException("Id is required.", nameof(id));
        }

        Id = id;
    }
}
