using CommunityHelper.Domain.Common;

namespace CommunityHelper.Domain.Entities;

/// <summary>
/// An Organization owned by an org admin user. New organizations are
/// unverified (<see cref="VerifiedAtUtc"/> is null = pending badge);
/// manual review is deferred out of Phase 1.
/// </summary>
public sealed class Organization
{
    private Organization(
        string id,
        string ownerUserId,
        string name,
        string type,
        List<string> causeTags,
        string location,
        string description,
        DateTime? verifiedAtUtc)
    {
        Id = id;
        OwnerUserId = ownerUserId;
        Name = name;
        Type = type;
        CauseTags = causeTags;
        Location = location;
        Description = description;
        VerifiedAtUtc = verifiedAtUtc;
    }

    public string Id { get; private set; }
    public string OwnerUserId { get; }
    public string Name { get; private set; }
    public string Type { get; private set; }
    public List<string> CauseTags { get; private set; }
    public string Location { get; private set; }
    public string Description { get; private set; }
    public DateTime? VerifiedAtUtc { get; }

    public static Organization Create(
        string ownerUserId,
        string name,
        string type,
        IEnumerable<string> causeTags,
        string location,
        string description,
        string? id = null)
    {
        if (string.IsNullOrWhiteSpace(ownerUserId))
        {
            throw new ArgumentException("Owner user id is required.", nameof(ownerUserId));
        }

        var organization = new Organization(
            id ?? string.Empty,
            ownerUserId,
            string.Empty,
            string.Empty,
            [],
            string.Empty,
            string.Empty,
            verifiedAtUtc: null);

        organization.Update(name, type, causeTags, location, description);
        return organization;
    }

    public void Update(
        string name,
        string type,
        IEnumerable<string> causeTags,
        string location,
        string description)
    {
        if (string.IsNullOrWhiteSpace(name))
        {
            throw new ArgumentException("Name is required.", nameof(name));
        }

        if (string.IsNullOrWhiteSpace(type))
        {
            throw new ArgumentException("Type is required.", nameof(type));
        }

        var normalizedTags = causeTags
            .Select(t => InputSanitizer.Clean(t))
            .Where(t => t.Length > 0)
            .ToList();

        if (normalizedTags.Count == 0)
        {
            throw new ArgumentException("At least one cause tag is required.", nameof(causeTags));
        }

        if (string.IsNullOrWhiteSpace(location))
        {
            throw new ArgumentException("Location is required.", nameof(location));
        }

        if (string.IsNullOrWhiteSpace(description))
        {
            throw new ArgumentException("Description is required.", nameof(description));
        }

        Name = InputSanitizer.Clean(name);
        Type = InputSanitizer.Clean(type);
        CauseTags = normalizedTags;
        Location = InputSanitizer.Clean(location);
        Description = InputSanitizer.CleanMultiline(description);
    }

    /// <summary>
    /// Rebuilds an organization from persisted state without re-running
    /// creation rules. Persistence use only.
    /// </summary>
    public static Organization Rehydrate(
        string id,
        string ownerUserId,
        string name,
        string type,
        List<string> causeTags,
        string location,
        string description,
        DateTime? verifiedAtUtc) =>
        new(id, ownerUserId, name, type, causeTags, location, description, verifiedAtUtc);

    /// <summary>
    /// Assigns the identifier generated by the persistence layer on insert.
    /// </summary>
    public void SetId(string id)
    {
        if (string.IsNullOrWhiteSpace(id))
        {
            throw new ArgumentException("Id is required.", nameof(id));
        }

        Id = id;
    }
}
