namespace CommunityHelper.Domain.Entities;

/// <summary>
/// A rotating refresh token. Only the SHA-256 hash is stored; the raw token
/// is shown to the client once. Rotation revokes the presented token and
/// links it to its replacement so reuse can be detected (reuse revokes the
/// whole token family).
/// </summary>
public sealed class RefreshToken
{
    private RefreshToken(
        string id,
        string tokenHash,
        string userId,
        DateTime createdAtUtc,
        DateTime expiresAtUtc,
        DateTime? revokedAtUtc,
        string? replacedByTokenHash)
    {
        Id = id;
        TokenHash = tokenHash;
        UserId = userId;
        CreatedAtUtc = createdAtUtc;
        ExpiresAtUtc = expiresAtUtc;
        RevokedAtUtc = revokedAtUtc;
        ReplacedByTokenHash = replacedByTokenHash;
    }

    public string Id { get; private set; }
    public string TokenHash { get; }
    public string UserId { get; }
    public DateTime CreatedAtUtc { get; }
    public DateTime ExpiresAtUtc { get; }
    public DateTime? RevokedAtUtc { get; private set; }
    public string? ReplacedByTokenHash { get; private set; }

    public bool IsExpired(DateTime utcNow) => utcNow >= ExpiresAtUtc;
    public bool IsRevoked => RevokedAtUtc.HasValue;
    public bool IsActive(DateTime utcNow) => !IsRevoked && !IsExpired(utcNow);

    public static RefreshToken Create(
        string tokenHash,
        string userId,
        DateTime expiresAtUtc,
        string? id = null)
    {
        if (string.IsNullOrWhiteSpace(tokenHash))
        {
            throw new ArgumentException("Token hash is required.", nameof(tokenHash));
        }

        if (string.IsNullOrWhiteSpace(userId))
        {
            throw new ArgumentException("User id is required.", nameof(userId));
        }

        if (expiresAtUtc <= DateTime.UtcNow)
        {
            throw new ArgumentException("Expiry must be in the future.", nameof(expiresAtUtc));
        }

        return new RefreshToken(
            id ?? string.Empty,
            tokenHash,
            userId,
            DateTime.UtcNow,
            expiresAtUtc,
            revokedAtUtc: null,
            replacedByTokenHash: null);
    }

    /// <summary>
    /// Rebuilds a token from persisted state without re-running creation
    /// rules (stored tokens may already be expired or revoked).
    /// Persistence use only.
    /// </summary>
    public static RefreshToken Rehydrate(
        string id,
        string tokenHash,
        string userId,
        DateTime createdAtUtc,
        DateTime expiresAtUtc,
        DateTime? revokedAtUtc,
        string? replacedByTokenHash) =>
        new(id, tokenHash, userId, createdAtUtc, expiresAtUtc, revokedAtUtc, replacedByTokenHash);

    /// <summary>
    /// Marks this token as rotated out, linking to the replacement token hash.
    /// </summary>
    public void Revoke(string? replacedByTokenHash = null)
    {
        RevokedAtUtc ??= DateTime.UtcNow;
        ReplacedByTokenHash ??= replacedByTokenHash;
    }

    /// <summary>
    /// Assigns the identifier generated by the persistence layer on insert.
    /// </summary>
    public void SetId(string id)
    {
        if (string.IsNullOrWhiteSpace(id))
        {
            throw new ArgumentException("Id is required.", nameof(id));
        }

        Id = id;
    }
}
