using CommunityHelper.Domain.Common;

namespace CommunityHelper.Domain.Entities;

/// <summary>
/// An authenticated identity. A user is either a Volunteer or an
/// Organization admin (<see cref="UserRoles"/>); the role is fixed at
/// registration and carried in the JWT role claim.
/// </summary>
public sealed class User
{
    private User(
        string id,
        string email,
        string passwordHash,
        string role,
        DateTime createdAtUtc,
        string? googleSubjectId)
    {
        Id = id;
        Email = email;
        PasswordHash = passwordHash;
        Role = role;
        CreatedAtUtc = createdAtUtc;
        GoogleSubjectId = googleSubjectId;
    }

    public string Id { get; private set; }
    public string Email { get; }
    public string PasswordHash { get; private set; }
    public string Role { get; }
    public DateTime CreatedAtUtc { get; }
    public string? GoogleSubjectId { get; private set; }

    public static User Create(
        string email,
        string passwordHash,
        string role,
        string? id = null,
        string? googleSubjectId = null)
    {
        if (string.IsNullOrWhiteSpace(email))
        {
            throw new ArgumentException("Email is required.", nameof(email));
        }

        if (string.IsNullOrWhiteSpace(passwordHash))
        {
            throw new ArgumentException("Password hash is required.", nameof(passwordHash));
        }

        if (!UserRoles.IsKnown(role))
        {
            throw new ArgumentException($"Unknown role '{role}'.", nameof(role));
        }

        return new User(
            id ?? string.Empty,
            InputSanitizer.Clean(email).ToLowerInvariant(),
            passwordHash,
            role,
            DateTime.UtcNow,
            googleSubjectId);
    }

    /// <summary>
    /// Rebuilds a user from persisted state without re-running creation rules.
    /// Persistence use only.
    /// </summary>
    public static User Rehydrate(
        string id,
        string email,
        string passwordHash,
        string role,
        DateTime createdAtUtc,
        string? googleSubjectId = null) =>
        new(id, email, passwordHash, role, createdAtUtc, googleSubjectId);

    /// <summary>
    /// Assigns the identifier generated by the persistence layer on insert.
    /// </summary>
    public void SetId(string id)
    {
        if (string.IsNullOrWhiteSpace(id))
        {
            throw new ArgumentException("Id is required.", nameof(id));
        }

        Id = id;
    }

    public void SetPasswordHash(string passwordHash)
    {
        if (string.IsNullOrWhiteSpace(passwordHash))
        {
            throw new ArgumentException("Password hash is required.", nameof(passwordHash));
        }

        PasswordHash = passwordHash;
    }

    public void LinkGoogleSubject(string subjectId)
    {
        if (string.IsNullOrWhiteSpace(subjectId))
        {
            throw new ArgumentException("Google subject id is required.", nameof(subjectId));
        }

        GoogleSubjectId = subjectId;
    }
}
