using CommunityHelper.Domain.Common;

namespace CommunityHelper.Domain.Entities;

/// <summary>
/// A Volunteer's public profile: skills, availability, causes, location, bio.
/// One profile per user; only the owning user may create or edit it.
/// </summary>
public sealed class VolunteerProfile
{
    private VolunteerProfile(
        string id,
        string userId,
        List<string> skills,
        string availability,
        List<string> causes,
        string location,
        string bio)
    {
        Id = id;
        UserId = userId;
        Skills = skills;
        Availability = availability;
        Causes = causes;
        Location = location;
        Bio = bio;
    }

    public string Id { get; private set; }
    public string UserId { get; }
    public List<string> Skills { get; private set; }
    public string Availability { get; private set; }
    public List<string> Causes { get; private set; }
    public string Location { get; private set; }
    public string Bio { get; private set; }

    public static VolunteerProfile Create(
        string userId,
        IEnumerable<string> skills,
        string availability,
        IEnumerable<string> causes,
        string location,
        string bio,
        string? id = null)
    {
        if (string.IsNullOrWhiteSpace(userId))
        {
            throw new ArgumentException("User id is required.", nameof(userId));
        }

        var profile = new VolunteerProfile(
            id ?? string.Empty,
            userId,
            [],
            string.Empty,
            [],
            string.Empty,
            string.Empty);

        profile.Update(skills, availability, causes, location, bio);
        return profile;
    }

    public void Update(
        IEnumerable<string> skills,
        string availability,
        IEnumerable<string> causes,
        string location,
        string bio)
    {
        var normalizedSkills = NormalizeList(skills, nameof(skills));
        var normalizedCauses = NormalizeList(causes, nameof(causes));

        if (string.IsNullOrWhiteSpace(availability))
        {
            throw new ArgumentException("Availability is required.", nameof(availability));
        }

        if (string.IsNullOrWhiteSpace(location))
        {
            throw new ArgumentException("Location is required.", nameof(location));
        }

        if (string.IsNullOrWhiteSpace(bio))
        {
            throw new ArgumentException("Bio is required.", nameof(bio));
        }

        Skills = normalizedSkills;
        Availability = InputSanitizer.Clean(availability);
        Causes = normalizedCauses;
        Location = InputSanitizer.Clean(location);
        Bio = InputSanitizer.CleanMultiline(bio);
    }

    /// <summary>
    /// Assigns the identifier generated by the persistence layer on insert.
    /// </summary>
    public void SetId(string id)
    {
        if (string.IsNullOrWhiteSpace(id))
        {
            throw new ArgumentException("Id is required.", nameof(id));
        }

        Id = id;
    }

    private static List<string> NormalizeList(IEnumerable<string> values, string paramName)
    {
        var list = values
            .Select(v => InputSanitizer.Clean(v))
            .Where(v => v.Length > 0)
            .ToList();

        if (list.Count == 0)
        {
            throw new ArgumentException($"At least one {paramName} entry is required.", paramName);
        }

        return list;
    }
}
